language: python
python:
  - 3.7
before_install:
  - pip install -U pip
install:
  - pip install ".[test]" . # install package + test dependencies
script: nosetests # run tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ZCAdSPIWnSsly4RdPBRI8wGsQrmh5k5IhkpVW6f/Z+YQEUXqVjDT0+72SBKbbeO1mhpAUMG1AXBq/ajLEPGZnTtzMF8wSFAkVJhWVIV7TXQC40fB8iNTm1o0lYZRiiELkOtiTYG0cM7kcCDkYOv9VDh5FPllxpyL7cIkwAMiQGCQ1ygzcvovHEMeNv/qg6U8p2wQpapJ6/hKiAASMbJvMzaADRPakBFVt3o+G75jRinqt+eFkKWJx7alXDtqQdkW9VV/KyVfRImjhJO5t3zxg9080muGIpXqh4z5Hl8PS9zRBaCEdbeJQki2AyMJ4yGT3Dz3THjIg+vvEIq4oGFStyAONsLok/1qthkE1EPOWkD8Bl7//goZ/J7NrqCxsjgCGGWvN4hvmZP/pv/63IrBebp+Bihg0UqYEXH4lClkzIPKDa5LoOg4xvjE5yu9ePMqr5hsFXswYH8TrR6dREYpEP4RAB9Jbwr20ObzMSSdOq7KglOenxD1UguC810kqVF+DIELSHyx2oAB1swSHWDAOP0COHT/lc4WN+z/Tt9QwiJK3KAxV9bic+7odx/6brvLwwxtMudX9A55jJWkuirY/ylUzq4CV09GWwHmgz/KWMv225JN67Q1tbA3wx/tQQgArXTuW9qcjHESF1y3YLZm8jrZfZgM65HY8rD03LOYVUM=
after_success:
  - codecov